### ISSUE TITLE
lazyload routes

### ISSUE THREAD

**Issue by christopherdarling** [jgallen23/routie#14]
Is there any way of adding additional routes without causing a routie.reload?

e.g.
current hash is #text
```javascript
routie('text', textFn);
if (imagesExist()) {
  routie('images', imagesFn);
}
```

results in textFn being triggered twice

**Comment by CtrlC-Root** [comment]
@christopherdarling This is indeed a duplicate. I'm going to close the issue but feel free to continue the discussion in #30.
