### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yagmikita** [jgallen23/routie#21]
Hello!
Can you, please, provide some kind of components extraction from routie?
For example: somewhere in the code (not in the routie callback) I can access routing params, ex.:
var id = rouie('getPathComponents', 'id');
or
routie('getPathComponents', function(components) {
  var controller = components[0];
  var action = components[1]
  var param1 = components[2];
});
Thanks for the lib :)

**Comment by CtrlC-Root** [comment]
@yagmikita Your use case seems to be viable using the current functionality. I'm going to close this issue, but if you would like to see some better handling of routes, go ahead and open another issue for that or submit a pull request.
