### ISSUE TITLE
Inconsistency in documentation

### ISSUE THREAD

**Issue by schjetne** [jgallen23/routie#27]
On http://projects.jga.me/routie/ it says this about optional parameters:

```javascript
routie('users/?:name', function(name) {
    //name == undefined
    //then
    //name == bob
});
routie('users/');
routie('users/bob');
```

But here on GitHub the documentation says this:

```javascript
routie('users/:name?', function(name) {
    //name == undefined
    //then
    //name == bob
});
routie('users/');
routie('users/bob');
```

*?:name* or *:name?*
Which is the correct one?

**Comment by Stoney-FD** [comment]
+1, if you want a PR, I'd happy to make one

**Comment by jgallen23** [comment]
yeah, that'd be great

**Comment by CtrlC-Root** [comment]
@frostney Would you still be interested in creating a pull request for this?

**Comment by frostney** [comment]
I apologize, I completely forgot the about this issue. Thanks for the ping. I'll do a pull request shortly.

**Comment by CtrlC-Root** [comment]
@frostney No worries, I was just going through the issues to try and close some.
