### ISSUE TITLE
Documentation typo, http://projects.jga.me/routie/#toc3

### ISSUE THREAD

**Issue by mateuszjarzewski** [jgallen23/routie#41]
http://projects.jga.me/routie/#toc3, in Advanced section, you've got:
```
routie('users/?:name', …
```
should be:
``` 
routie('users/:name?', …
```

**Comment by CtrlC-Root** [comment]
@mateuszjarzewski This looks like a duplicate of #27. I'm closing this issue but feel free to continue the conversation in there.
